# Generated by Django 3.2.15 on 2022-09-30 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'verbose_name': 'ингредиент для рецепта', 'verbose_name_plural': 'ингредиенты для рецепта'},
        ),
    ]
