# Generated by Django 3.2.15 on 2022-10-04 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_alter_ingredientsamount_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsamount',
            name='amount_min_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='cooking_time_min_constraint',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='in_shoping_cart',
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_shopping_cart',
            field=models.ManyToManyField(help_text='Рецепты в корзине.', related_name='shopping_recipes', through='recipe.ShopingCart', to=settings.AUTH_USER_MODEL, verbose_name='рецепты в корзине'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Изображение: ммм нямка!', upload_to='', verbose_name='изображение: ммм нямка!'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='recipe',
            field=models.ForeignKey(help_text='Рецепт в корзине.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='recipe.recipe', verbose_name='покупки'),
        ),
        migrations.AlterField(
            model_name='shopingcart',
            name='user',
            field=models.ForeignKey(help_text='Владелец корзины.', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='покупатель'),
        ),
    ]
